-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "pending_payment" SET DEFAULT 0.0,
ALTER COLUMN "pending_payment" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "deposit" SET DEFAULT 0.0,
ALTER COLUMN "deposit" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sales" ALTER COLUMN "total_amount_received" SET DEFAULT 0.0,
ALTER COLUMN "total_amount_received" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bal_payment" SET DEFAULT 0.0,
ALTER COLUMN "bal_payment" SET DATA TYPE DOUBLE PRECISION;
